#!/bin/bash

sudo sh -c 'echo "deb http://packages.ros.org/ros/ubuntu $(lsb_release -sc) main" > /etc/apt/sources.list.d/ros-latest.list'
sudo apt-key adv --keyserver hkp://ha.pool.sks-keyservers.net:80 --recv-key 421C365BD9FF1F717815A3895523BAEEB01FA116

sudo apt-get update
sudo apt-get install terminator emacs ros-kinetic-desktop-full -y

timedatectl set-local-rtc 1 --adjust-system-clock

cp -r .bash_aliases ~/
cp -r .bashrc ~/
cp -r .touchpad ~/
cp -r .emacs.d ~/

source ~/.bashrc
